WebApplication1/Models/Medicine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Medicine
    {
        public int MedicineID { set; get; }
       [DisplayName("Medicine Name")]
        public string MedidineName { set; get; }
        [DisplayName( "Power")]
        public string Power { set; get; }
      // public virtual ICollection<Disease> Diseases { set; get; }
    }
}

WebApplication1/Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using MVC_part1.Models;

namespace WebApplication1.Controllers
{
    public class MedicineController : Controller
    {
        private StudentGatewayDB db = new StudentGatewayDB();

        // GET: /Medicine/
        public ActionResult Index()
        {
            return View(db.Medicines.ToList());
        }

        // GET: /Medicine/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // GET: /Medicine/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Medicine/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="MedicineID,MedidineName,MgMl")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Medicines.Add(medicine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medicine);
        }

        // GET: /Medicine/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: /Medicine/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="MedicineID,MedidineName,MgMl")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medicine);
        }

        // GET: /Medicine/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: /Medicine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicine medicine = db.Medicines.Find(id);
            db.Medicines.Remove(medicine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult MedicineSetup()
        {
            return View();
        }

        public ActionResult MedicinceSave(string Name, string Power)
        {
            Medicine medicine = new Medicine();
            medicine.MedidineName = Name;
            medicine.Power = Power;
            db.Medicines.Add(medicine);
            db.SaveChanges();
           // return Json(aStudent, JsonRequestBehavior.AllowGet);
            //    Department aDepartment = new Department(){Code=code,Name = name};
            //db.Departments.Add(aDepartment);
            //db.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);

        }
    }
}

WebApplication1/Views/Medicine/Create.cshtml
@model WebApplication1.Models.Medicine

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicine</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MedidineName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedidineName)
                @Html.ValidationMessageFor(model => model.MedidineName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MgMl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MgMl)
                @Html.ValidationMessageFor(model => model.MgMl)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Medicine/Delete.cshtml
@model WebApplication1.Models.Medicine

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MedidineName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedidineName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MgMl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MgMl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Medicine/Details.cshtml
@model WebApplication1.Models.Medicine

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Medicine</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MedidineName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedidineName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MgMl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MgMl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MedicineID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Medicine/Edit.cshtml
@model WebApplication1.Models.Medicine

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicine</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.MedicineID)

        <div class="form-group">
            @Html.LabelFor(model => model.MedidineName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedidineName)
                @Html.ValidationMessageFor(model => model.MedidineName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MgMl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MgMl)
                @Html.ValidationMessageFor(model => model.MgMl)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Medicine/Index.cshtml
@model IEnumerable<WebApplication1.Models.Medicine>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MedidineName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MgMl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MedidineName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MgMl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MedicineID }) |
            @Html.ActionLink("Details", "Details", new { id=item.MedicineID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MedicineID })
        </td>
    </tr>
}

</table>

WebApplication1/Views/Medicine/MedicineSetup.cshtml
@{
    ViewBag.Title = "MedicineSetup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form class="form-horizontal">
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">Medicine Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="name" id="name" placeholder="Medicine Name">
        </div>
    </div>
    <div class="form-group">
        <label for="power" class="col-sm-2 control-label">Power</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="power" id="power" placeholder="Power">

            <select id="mgml">
                <option>--Select---</option>
                <option>mg</option>
                <option>ml</option>

            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button onclick=" appendText() ">Add</button>
        </div>
    </div>
</form>
@section Scripts {
    <script>
        function appendText() {
            var name = $("#name").val();
            var mgml = $("#power").val() +"-"+ $("#mgml").val();

            var mydata = { Name: name, Power: mgml };
            $.ajax({
                type: "POST",
                url: '@Url.Action("MedicinceSave", "Medicine")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(mydata),
                dataType: "json",
                success: function(data) {

                }
            });
            return false;
        }

    </script>

}